#!/usr/bin/env python

APP_NAME="mdns_browser"
TIME_BASE=1000

import os
import sys

cp=os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, cp)

GLADE_FILE_PATH=os.path.join(cp, "ui.glade")

import gobject  
import gtk

gobject.threads_init()  #@UndefinedVariable

from mdns_browser.system import mswitch
from mdns_browser.agents import sup
from mdns_browser.agents import debug
from mdns_browser.agents import comms
from mdns_browser.agents import logger
from mdns_browser.agents import querier
from mdns_browser.agents import listener
from mdns_browser.agents import cache
from mdns_browser.agents.ui import UiAgent


def main():
    try:
        from mdns_browser.agents.tray import TrayAgent
        _ta=TrayAgent(APP_NAME, "")

        _ua=UiAgent(TIME_BASE,GLADE_FILE_PATH)
        gobject.timeout_add(TIME_BASE, _ua.tick)

        gtk.main()
        
    except Exception,e:
        print "Exception: %s" % e
        mswitch.quit()
        sys.exit(1)

main()
